# Generated by Django 6.0.4 on 2026-05-19 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0003_alter_todo_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('citoyen', 'Citoyen'), ('juriste', 'Juriste'), ('psychologue', 'Psychologue'), ('ong', 'ONG / Association'), ('admin', 'Administrateur')], default='citoyen', max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('region', models.CharField(blank=True, choices=[('centre', 'Centre (Yaoundé)'), ('littoral', 'Littoral (Douala)'), ('ouest', 'Ouest (Bafoussam)'), ('nord', 'Nord (Garoua)'), ('extreme_nord', 'Extrême-Nord'), ('adamaoua', 'Adamaoua'), ('est', 'Est'), ('nord_ouest', 'Nord-Ouest'), ('sud', 'Sud'), ('sud_ouest', 'Sud-Ouest')], max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
