# Generated by Django 6.0.4 on 2026-05-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0004_profile_delete_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TexteLoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Ex: Article 275 - Meurtre', max_length=255)),
                ('contenu', models.TextField(help_text='Le texte complet de la loi')),
                ('categorie', models.CharField(choices=[('code_penal', 'Code Pénal'), ('code_civil', 'Code Civil'), ('code_travail', 'Code du Travail'), ('constitution', 'Constitution'), ('autre', 'Autre')], default='autre', max_length=50)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('mots_cles', models.CharField(blank=True, help_text='Mots clés pour faciliter la recherche', max_length=255)),
            ],
            options={
                'verbose_name': 'Texte de Loi',
                'verbose_name_plural': 'Textes de Loi',
                'ordering': ['-date_ajout'],
            },
        ),
    ]
