# Generated by Django 6.0.4 on 2026-06-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0005_texteloi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='region',
        ),
        migrations.AddField(
            model_name='profile',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='document_carte_pro',
            field=models.URLField(blank=True, help_text='Lien vers le scan de la carte pro stocké sur Supabase', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='document_cni',
            field=models.URLField(blank=True, help_text="Lien vers le scan de la pièce d'identité nationale (CNI)", null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='document_diplome',
            field=models.URLField(blank=True, help_text='Lien vers le scan du diplôme', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='est_certifie',
            field=models.BooleanField(default=False, help_text="Définit si l'expert a été validé manuellement par l'administrateur"),
        ),
        migrations.AddField(
            model_name='profile',
            name='nom_structure',
            field=models.CharField(blank=True, help_text="Nom du cabinet, de la clinique ou de l'ONG (lieu d'exercice des fonctions)", max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='numero_carte_professionnelle',
            field=models.CharField(blank=True, help_text="Numero d'ordre des avocats, psychologues ou agrement des ONG et association", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo_professionnelle',
            field=models.URLField(blank=True, help_text="Lien vers la photo de profil professionnelle de l'expert", null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('CITOYEN', 'Citoyen'), ('VICTIME_VBG', 'Victime de VBG'), ('JURISTE', 'Juriste / Avocat'), ('PSYCHOLOGUE', 'Psychologue'), ('ONG', 'ONG / Association de terrain'), ('ADMIN', 'Administrateur Systeme')], default='CITOYEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
