# Generated by Django 6.0.4 on 2026-06-10 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0006_remove_profile_region_profile_adresse_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeAssistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_reference', models.CharField(editable=False, help_text='Identifiant unique pour le suivi du dossier', max_length=50, unique=True)),
                ('titre', models.CharField(help_text='Ex: Licenciement abusif après 3 ans', max_length=255)),
                ('description', models.TextField(help_text='Description détaillée de la situation')),
                ('categorie', models.CharField(choices=[('VBG', 'Violence Basée sur le Genre (VBG)'), ('TRAVAIL', 'Droit du Travail / Licenciement'), ('FAMILLE', 'Droit de la Famille (Mariage, Divorce, Succession)'), ('FONCIER', 'Litige Foncier / Terrain'), ('PENAL', 'Affaires Pénales (Vol, Escroquerie, Agression)'), ('AUTRE', 'Autre problème juridique')], default='AUTRE', max_length=20)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', "En attente d'analyse"), ('APPROUVE', 'Approuvée (Dossier créé)'), ('REJETE', 'Rejetée / Classée sans suite')], default='EN_ATTENTE', max_length=20)),
                ('est_anonyme', models.BooleanField(default=False, help_text="Si vrai, masque l'identité réelle du citoyen aux experts assignés")),
                ('consentement_ong', models.BooleanField(default=False, help_text="Spécifique VBG : L'utilisateur accepte d'être contacté et suivi par une ONG")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('citoyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_assistance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Demande d'Assistance",
                'verbose_name_plural': "Demandes d'Assistance",
                'ordering': ['-date_creation'],
            },
        ),
    ]
