# Generated by Django 6.0.4 on 2026-06-10 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0007_demandeassistance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours de traitement'), ('RESOLU', 'Résolu / Clôturé avec succès'), ('ARCHIVE', 'Archivé / Classé')], default='EN_COURS', max_length=20)),
                ('notes_suivi_admin', models.TextField(blank=True, help_text="Remarques et coordination de l'administrateur système", null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('demande', models.OneToOneField(help_text="La demande d'assistance d'origine qui a déclenché ce dossier", on_delete=django.db.models.deletion.CASCADE, related_name='dossier', to='assistance.demandeassistance')),
                ('juriste_assigne', models.ForeignKey(blank=True, help_text="L'avocat ou parajuriste en charge de la procédure légale", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_juridiques', to=settings.AUTH_USER_MODEL)),
                ('ong_assignee', models.ForeignKey(blank=True, help_text="L'ONG ou association agréée pour la prise en charge sociale et l'hébergement", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_sociaux_ong', to=settings.AUTH_USER_MODEL)),
                ('psychologue_assigne', models.ForeignKey(blank=True, help_text='Le professionnel de la santé mentale pour le soutien psychologique', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_psychologiques', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dossier de Suivi',
                'verbose_name_plural': 'Dossiers de Suivi',
                'ordering': ['-date_creation'],
            },
        ),
    ]
